export { Dashboard } from './Dashboard'
export { Contatos } from './Contatos'
export { ContatoDetalhe } from './ContatoDetalhe'
export { NovaVenda } from './NovaVenda'
export { Vendas } from './Vendas'
export { VendaDetalhe } from './VendaDetalhe'
export { Ranking } from './Ranking'
export { Recompra } from './Recompra'
export { Configuracoes } from './Configuracoes'
export { Produtos } from './Produtos'
export { RelatorioFabrica } from './RelatorioFabrica'
export { Estoque } from './Estoque'
export { Entregas } from './Entregas'
export { PedidosCompra } from './PedidosCompra'
export { Menu } from './Menu'
export { CatalogoPendentes } from './CatalogoPendentes'
export { FluxoCaixa } from './FluxoCaixa'
export { PlanoDeContas } from './PlanoDeContas'
export { ContasAPagar } from './ContasAPagar'
export { LoginPage } from './LoginPage'


