// Utilities
export { cn } from './cn'

// Formatters
export {
    formatCurrency,
    formatPhone,
    cleanPhone,
    unformatPhone,
    formatDate,
    formatDateTime,
    formatRelativeDate,
    getWhatsAppLink,
    formatWeight,
    pluralize,
} from './formatters'

// Validators
export { isValidPhone } from './validators'

// Meta CAPI — normalização/hash das chaves de match
export {
    stripAccents,
    splitName,
    normalizeCity,
    normalizeState,
    normalizeZip,
    sha256Hex,
    hashField,
} from './metaNormalize'

// WhatsApp — chave canônica + parsing do webhook da Evolution
// `normalizePhone` (hash da Meta) mora aqui porque depende de `telefoneWa`.
export {
    telefoneWa,
    normalizePhone,
    telefoneWaDeJid,
    isJidIgnorado,
    extrairReferral,
    isAnuncioPago,
    podeGravarAtribuicao,
    lerCtwaClid,
    lerSourceId,
    extrairMensagensCruas,
    normalizarMensagem,
} from './whatsapp'
export type { TipoMidia, MensagemNormalizada } from './whatsapp'

// Secretária de WhatsApp — lógica pura (tempo de digitação, partição, gaiola)
export {
    calcularTempoDigitacaoMs,
    particionarResposta,
    humanoAssumiu,
    estaLiberado,
    pedidoVigente,
    JANELA_HUMANO_MS,
    JANELA_PEDIDO_MS,
} from './secretaria'
export type { MensagemDaConversa, IntencaoRegistrada } from './secretaria'

// Catálogo da secretária — resolver o que o cliente escreveu em produto real
// `ProdutoCatalogo` já é exportado por './types' (a view pública vw_catalogo_produtos,
// usada em 25+ arquivos de apps/catalogo). Nome igual nos dois causaria
// `TS2300: Duplicate identifier` e quebraria o typecheck do catálogo público — por isso
// o tipo da secretária sai com um nome próprio, sem tocar no contrato existente.
export { resolverTermo } from './catalogo'
export type { ProdutoCatalogo as ProdutoCatalogoSecretaria, Resolucao } from './catalogo'

// Database Types (generated by supabase gen types)
export type { Database, Json } from './database'

// Type aliases and helpers (manual)
export type {
    Tables,
    Enums,
    TablesInsert,
    TablesUpdate,
    Insert,
    Update,
    Conta,
    PlanoConta,
    Lancamento,
    ExtratoItem,
    FluxoResumo,
    Venda,
    Contato,
    Produto,
    ItemVenda,
    PagamentoVenda,
    PurchaseOrder,
    PurchaseOrderItem,
    PurchaseOrderPayment,
    ContaAPagar,
    PagamentoContaAPagar,
    VendaInsert,
    VendaUpdate,
    ContatoInsert,
    ContatoUpdate,
    ProdutoInsert,
    ProdutoUpdate,
    ItemVendaInsert,
    ProdutoCatalogo,
    SeloVariant,
    Secao,
    SecaoInsert,
    SecaoUpdate,
} from './types'
