// Utilities
export { cn } from './cn'

// Formatters
export {
    formatCurrency,
    formatPhone,
    cleanPhone,
    unformatPhone,
    formatDate,
    formatDateTime,
    formatRelativeDate,
    getWhatsAppLink,
    formatWeight,
    pluralize,
} from './formatters'

// Validators
export { isValidPhone } from './validators'

// Meta CAPI — normalização/hash das chaves de match
export {
    stripAccents,
    splitName,
    normalizeCity,
    normalizeState,
    normalizeZip,
    sha256Hex,
    hashField,
} from './metaNormalize'

// WhatsApp — chave canônica + parsing do webhook da Evolution
// `normalizePhone` (hash da Meta) mora aqui porque depende de `telefoneWa`.
export {
    telefoneWa,
    normalizePhone,
    telefoneWaDeJid,
    isJidIgnorado,
    extrairReferral,
    lerCtwaClid,
    lerSourceId,
    extrairMensagensCruas,
    normalizarMensagem,
} from './whatsapp'
export type { TipoMidia, MensagemNormalizada } from './whatsapp'

// Database Types (generated by supabase gen types)
export type { Database, Json } from './database'

// Type aliases and helpers (manual)
export type {
    Tables,
    Enums,
    TablesInsert,
    TablesUpdate,
    Insert,
    Update,
    Conta,
    PlanoConta,
    Lancamento,
    ExtratoItem,
    FluxoResumo,
    Venda,
    Contato,
    Produto,
    ItemVenda,
    PagamentoVenda,
    PurchaseOrder,
    PurchaseOrderItem,
    PurchaseOrderPayment,
    ContaAPagar,
    PagamentoContaAPagar,
    VendaInsert,
    VendaUpdate,
    ContatoInsert,
    ContatoUpdate,
    ProdutoInsert,
    ProdutoUpdate,
    ItemVendaInsert,
    ProdutoCatalogo,
    SeloVariant,
    Secao,
    SecaoInsert,
    SecaoUpdate,
} from './types'
