// Utilities
export { cn } from './cn'

// Formatters
export {
    formatCurrency,
    formatPhone,
    cleanPhone,
    unformatPhone,
    formatDate,
    formatDateTime,
    formatRelativeDate,
    getWhatsAppLink,
    formatWeight,
    pluralize,
} from './formatters'

// Validators
export { isValidPhone } from './validators'

// Database Types (generated by supabase gen types)
export type { Database, Json } from './database'

// Type aliases and helpers (manual)
export type {
    Tables,
    Enums,
    TablesInsert,
    TablesUpdate,
    Insert,
    Update,
    Conta,
    PlanoConta,
    Lancamento,
    ExtratoItem,
    FluxoResumo,
    Venda,
    Contato,
    Produto,
    ItemVenda,
    PagamentoVenda,
    PurchaseOrder,
    PurchaseOrderItem,
    PurchaseOrderPayment,
    ContaAPagar,
    PagamentoContaAPagar,
    VendaInsert,
    VendaUpdate,
    ContatoInsert,
    ContatoUpdate,
    ProdutoInsert,
    ProdutoUpdate,
    ItemVendaInsert,
    ProdutoCatalogo,
    PedidoCatalogo,
    ItemPedidoCatalogo,
    ImagemProdutoCatalogo,
} from './types'
